version: '2'

services:
  maven:
    image: maven:3.8-openjdk-18
    working_dir: /home/maven/project
    volumes:
      - ./:/home/maven/project
  # Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.37.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"