version: '3.3'

services:
  maven:
    image: maven:3.8-openjdk-18
    working_dir: /home/maven/project
    networks:
      - elk
    volumes:
      - ./:/home/maven/project
    extra_hosts:
      - "logstash:172.21.0.1"

  elasticsearch:
    container_name: elasticsearch
    image: docker.io/elastic/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    networks:
      - elk
  logstash:
    container_name: logstash
    image: docker.io/elastic/logstash:7.16.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipelines:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "127.0.0.1:12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.io/elastic/kibana:7.16.3
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge